#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter, defaultdict
from datetime import datetime
from pathlib import Path
from typing import Iterable

import matplotlib.pyplot as plt

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from toolcalltokenization.trace_utils import load_jsonl  # noqa: E402


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Summarize OttoAuth collection health, including local trace completeness and usable canonical episodes."
    )
    parser.add_argument(
        "--traces-root",
        default=str(ROOT / "data" / "ottoauth"),
        help="Root folder containing OttoAuth task/trace folders.",
    )
    parser.add_argument(
        "--canonical-jsonl",
        default=str(ROOT / "outputs" / "ottoauth_live_collection" / "canonical_trace.jsonl"),
        help="Canonical JSONL generated by ingest_ottoauth_collection.py.",
    )
    parser.add_argument(
        "--audit-json",
        default=str(ROOT / "outputs" / "ottoauth_collection_audit.json"),
        help="Audit JSON generated by audit_ottoauth_collection.mjs.",
    )
    parser.add_argument(
        "--output-json",
        default=str(ROOT / "outputs" / "ottoauth_collection_health.json"),
        help="Where to write the health summary JSON.",
    )
    parser.add_argument(
        "--output-figure",
        default=str(ROOT / "docs" / "figures" / "ottoauth_collection_health.svg"),
        help="Where to write the health figure.",
    )
    return parser.parse_args()


def load_json(path: Path) -> dict:
    with open(path, "r", encoding="utf-8") as handle:
        return json.load(handle)


def parse_iso(value: str | None) -> datetime | None:
    if not value:
        return None
    try:
        return datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return None


def iter_trace_dirs(root: Path) -> Iterable[Path]:
    for trace_path in sorted(root.rglob("trace.json")):
        if (trace_path.parent / "task.json").is_file():
            yield trace_path.parent


def summarize_local_traces(traces_root: Path) -> dict:
    records = []
    for trace_dir in iter_trace_dirs(traces_root):
        task_payload = load_json(trace_dir / "task.json")
        trace_payload = load_json(trace_dir / "trace.json")
        task = task_payload.get("task", {}) if isinstance(task_payload.get("task"), dict) else {}
        website = trace_dir.parent.name
        tool_use_events = [
            event
            for event in trace_payload.get("events", []) or []
            if isinstance(event, dict) and event.get("type") == "tool_use"
        ]
        records.append(
            {
                "task_id": str(trace_payload.get("taskId") or task.get("id") or trace_dir.name),
                "website": website,
                "trace_dir": str(trace_dir),
                "status": str(trace_payload.get("status") or "<missing>"),
                "started_at": trace_payload.get("startedAt"),
                "completed_at": trace_payload.get("completedAt"),
                "events": len(trace_payload.get("events", []) or []),
                "messages": len(trace_payload.get("messages", []) or []),
                "tool_use_events": len(tool_use_events),
                "usable": len(tool_use_events) > 0 and str(trace_payload.get("status") or "") == "completed",
            }
        )

    status_counts = Counter(record["status"] for record in records)
    website_counts = Counter(record["website"] for record in records)
    usable_counts = Counter(record["website"] for record in records if record["usable"])
    partial_records = [
        record
        for record in records
        if not record["usable"] or record["status"] != "completed"
    ]

    cumulative_local = []
    cumulative_usable = []
    local_total = 0
    usable_total = 0
    for record in sorted(records, key=lambda item: parse_iso(item["started_at"]) or datetime.min):
        local_total += 1
        if record["usable"]:
            usable_total += 1
        timestamp = record["completed_at"] or record["started_at"]
        cumulative_local.append({"at": timestamp, "count": local_total})
        cumulative_usable.append({"at": timestamp, "count": usable_total})

    return {
        "records": records,
        "local_trace_folders": len(records),
        "status_counts": dict(status_counts),
        "website_counts": dict(website_counts),
        "usable_counts": dict(usable_counts),
        "usable_trace_folders": sum(1 for record in records if record["usable"]),
        "partial_or_nonusable_records": partial_records,
        "cumulative_local": cumulative_local,
        "cumulative_usable": cumulative_usable,
    }


def summarize_canonical(canonical_jsonl: Path) -> dict:
    rows = load_jsonl(str(canonical_jsonl)) if canonical_jsonl.exists() else []
    episodes_by_site: dict[str, set[str]] = defaultdict(set)
    rows_by_site: Counter[str] = Counter()
    for row in rows:
        site = str(row.get("website") or "<missing>")
        episode_id = str(row.get("episode_id") or "<missing>")
        episodes_by_site[site].add(episode_id)
        rows_by_site[site] += 1
    return {
        "canonical_rows": len(rows),
        "canonical_episode_counts": {
            site: len(episode_ids)
            for site, episode_ids in sorted(episodes_by_site.items())
        },
        "canonical_row_counts": dict(rows_by_site),
    }


def summarize_audit(audit_json: Path) -> dict:
    if not audit_json.exists():
        return {}
    audit = load_json(audit_json)
    missing_completed = audit.get("missing_completed_recordings", []) or []
    return {
        "local_recorded_task_count": int(audit.get("local_recorded_task_count") or 0),
        "server_completed_task_count": int(audit.get("server_completed_task_count") or 0),
        "server_failed_task_count": int(audit.get("server_failed_task_count") or 0),
        "missing_completed_recordings": len(missing_completed),
        "missing_completed_amazon": sum(
            1
            for item in missing_completed
            if "amazon.com" in str(item.get("task_prompt") or "")
        ),
    }


def build_health_summary(local_summary: dict, canonical_summary: dict, audit_summary: dict) -> dict:
    server_completed = int(audit_summary.get("server_completed_task_count") or 0)
    local_recorded = int(audit_summary.get("local_recorded_task_count") or local_summary["local_trace_folders"])
    usable_local = int(local_summary["usable_trace_folders"])
    canonical_amazon = int(canonical_summary.get("canonical_episode_counts", {}).get("amazon.com", 0))

    def safe_ratio(num: int, den: int) -> float | None:
        if den <= 0:
            return None
        return round(num / den, 4)

    warnings = []
    recorded_ratio = safe_ratio(local_recorded, server_completed)
    usable_ratio = safe_ratio(usable_local, server_completed)
    if recorded_ratio is not None and recorded_ratio < 0.8:
        warnings.append("Local recording coverage is below 80% of server-completed tasks.")
    if usable_ratio is not None and usable_ratio < 0.8:
        warnings.append("Usable local traces are below 80% of server-completed tasks.")
    if local_summary["partial_or_nonusable_records"]:
        warnings.append("Some local trace folders are partial or non-usable and should not be mined yet.")

    if recorded_ratio is None:
        recommendation = "No server audit available yet. Refresh the audit before scaling collection."
    elif recorded_ratio < 0.8:
        recommendation = (
            "Pause expensive collection campaigns until recorder coverage improves; the current trace loss rate is too high."
        )
    elif usable_ratio is not None and usable_ratio < 0.8:
        recommendation = (
            "Collection is partially healthy, but keep campaigns small until more locally recorded traces finish cleanly."
        )
    else:
        recommendation = "Collection health looks good enough to scale repeated site-family campaigns."

    return {
        "generated_at": datetime.utcnow().isoformat(timespec="seconds") + "Z",
        "local_trace_folders": local_summary["local_trace_folders"],
        "usable_trace_folders": usable_local,
        "canonical_episode_counts": canonical_summary.get("canonical_episode_counts", {}),
        "audit": audit_summary,
        "audit_summary": audit_summary,
        "ratios": {
            "local_recorded_vs_server_completed": recorded_ratio,
            "usable_local_vs_server_completed": usable_ratio,
            "amazon_usable_vs_local_trace_folders": safe_ratio(canonical_amazon, local_summary["local_trace_folders"]),
        },
        "warnings": warnings,
        "recommendation": recommendation,
        "local_status_counts": local_summary["status_counts"],
        "local_website_counts": local_summary["website_counts"],
        "local_usable_counts": local_summary["usable_counts"],
        "partial_or_nonusable_records": local_summary["partial_or_nonusable_records"],
        "cumulative_local": local_summary["cumulative_local"],
        "cumulative_usable": local_summary["cumulative_usable"],
    }


def dump_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def render_figure(summary: dict, output_path: Path) -> None:
    plt.style.use("default")
    plt.rcParams.update({"figure.dpi": 160, "savefig.dpi": 160, "font.size": 10})

    fig, axes = plt.subplots(2, 1, figsize=(10.8, 7.6), gridspec_kw={"height_ratios": [1.1, 1.4]})

    audit = summary["audit"]
    categories = ["Server completed", "Local folders", "Usable local", "Canonical amazon"]
    values = [
        int(audit.get("server_completed_task_count") or 0),
        int(summary["local_trace_folders"]),
        int(summary["usable_trace_folders"]),
        int(summary["canonical_episode_counts"].get("amazon.com", 0)),
    ]
    colors = ["#3d5a80", "#2a9d8f", "#4caf50", "#c46b32"]
    axes[0].bar(categories, values, color=colors)
    axes[0].set_ylabel("Count")
    axes[0].set_title("OttoAuth Collection Health")
    axes[0].grid(axis="y", alpha=0.25)

    local_points = summary["cumulative_local"]
    usable_points = summary["cumulative_usable"]
    xs = list(range(1, len(local_points) + 1))
    axes[1].plot(xs, [point["count"] for point in local_points], marker="o", linewidth=2.2, color="#3d5a80", label="Local folders")
    axes[1].plot(xs, [point["count"] for point in usable_points], marker="o", linewidth=2.2, color="#2a9d8f", label="Usable local traces")
    axes[1].set_xlabel("Local trace arrival order")
    axes[1].set_ylabel("Cumulative count")
    axes[1].set_ylim(bottom=0)
    axes[1].grid(alpha=0.25)
    axes[1].legend(loc="best")

    fig.tight_layout()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, bbox_inches="tight")
    plt.close(fig)


def main() -> None:
    args = parse_args()
    traces_root = Path(args.traces_root)
    canonical_jsonl = Path(args.canonical_jsonl)
    audit_json = Path(args.audit_json)
    output_json = Path(args.output_json)
    output_figure = Path(args.output_figure)

    local_summary = summarize_local_traces(traces_root)
    canonical_summary = summarize_canonical(canonical_jsonl)
    audit_summary = summarize_audit(audit_json)
    summary = build_health_summary(local_summary, canonical_summary, audit_summary)

    dump_json(output_json, summary)
    render_figure(summary, output_figure)


if __name__ == "__main__":
    main()
